services:
    _defaults:
        public: false
        autoconfigure: false
        autowire: false

    bastsys.state_bundle.listener.state_changed_convert:
        class: App\ResourceBundle\EventListener\StateChangedEventConvertListener
        arguments:
            - '@event_dispatcher'
        tags:
            - {name: doctrine.event_listener, event: App\ResourceBundle\Event\StateChangedEventArgs}
